### ISSUE TITLE
Booster catalog factory test to use in memory git server

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/arquillian-organization#1]
As part of improving OSIO stability we brought in-memory git server for both [booster-catalog-service](https://github.com/fabric8-launcher/launcher-booster-catalog-service/pull/14) and [launcher-backend](https://github.com/fabric8-launcher/launcher-backend/pull/13). 

- [x] bring in-memory git server as in the PRs mentioned above
- [x] use `system-rules` instead of `System.setProperty`

In a similar way we should make improve other tests relying on GitHub repositories, such as [1]

[1] https://github.com/fabric8-launcher/launcher-backend/blob/e94e3ac10fb6e1a282cb4ad6533e72633a90df69/addons/launcher-addon/src/test/java/io/fabric8/launcher/addon/BoosterCatalogFactoryTest.java#L19

**Comment by dipak-pawar** [comment]
Submitted - https://github.com/bartoszmajsak/launcher-backend/pull/1
