### ISSUE TITLE
Bring service virtualization for GitLab service

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/arquillian-organization#12]
Similarly to Service Virtualization for GitHub (https://github.com/fabric8-launcher/launcher-backend/pull/37), introduce the same strategy for [GitLab integration tests](https://github.com/fabric8-launcher/launcher-backend/blob/2e4ca92620de70b6cfabb557739358a933085289/services/git-service-impl/src/test/java/io/fabric8/launcher/service/gitlab/impl/GitLabServiceIT.java).

**Comment by dipak-pawar** [comment]
PR - https://github.com/fabric8-launcher/launcher-backend/pull/71
